import React, { useEffect, useState } from 'react';
import { Transaction } from '../types';
import { cn } from '../lib/utils';
import { Search, Filter, Download, FileText, FileSpreadsheet, Printer } from 'lucide-react';
import jsPDF from 'jspdf';

export default function TransactionHistory() {
  const [history, setHistory] = useState<Transaction[]>([]);
  const [searchTerm, setSearchTerm] = useState('');

  useEffect(() => {
    fetch('/api/transactions')
      .then(r => r.json())
      .then(data => {
        // Duplicate and reverse to simulate a larger "history"
        setHistory([...data.transactions, ...data.transactions].map((t, i) => ({...t, id: t.id + "-" + i})));
      });
  }, []);

  const getRiskColor = (level: string) => {
    switch (level) {
      case 'Low': return 'bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20';
      case 'Medium': return 'bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20';
      case 'High': return 'bg-rose-500/10 text-rose-600 dark:text-rose-400 border-rose-500/20';
      case 'Blocked': return 'bg-red-600/10 text-red-600 dark:text-red-500 border-red-600/20';
      default: return 'bg-slate-500/10 text-slate-600 dark:text-slate-400 border-slate-500/20';
    }
  };

  const downloadReport = (tx: Transaction) => {
    const doc = new jsPDF();
    
    doc.setFont("helvetica", "bold");
    doc.setFontSize(22);
    doc.text("FraudGuard", 20, 20);
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100);
    doc.text("Fraud Detection Analysis Report (Historical)", 20, 28);
    
    doc.setDrawColor(200);
    doc.line(20, 32, 190, 32);
    
    doc.setTextColor(0);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("Transaction Details", 20, 45);
    
    doc.setFontSize(11);
    doc.setFont("helvetica", "normal");
    doc.text(`Transaction ID: ${tx.id}`, 20, 55);
    doc.text(`Date & Time: ${new Date(tx.timestamp).toLocaleString()}`, 20, 62);
    doc.text(`Amount: $${tx.amount.toFixed(2)}`, 20, 69);
    doc.text(`Transaction Type: ${tx.category}`, 20, 76);
    
    doc.text(`Merchant: ${tx.merchant}`, 110, 55);
    doc.text(`Location: ${tx.location}`, 110, 62);
    doc.text(`Device Information: ${tx.device}`, 110, 69);
    doc.text(`IP Address: ${tx.ip_address}`, 110, 76);

    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.text("AI Prediction Result", 20, 95);
    
    doc.setFontSize(11);
    if (tx.risk_level === 'High' || tx.risk_level === 'Blocked') doc.setTextColor(200, 0, 0);
    else if (tx.risk_level === 'Medium') doc.setTextColor(200, 150, 0);
    else doc.setTextColor(0, 150, 0);
    
    doc.setFont("helvetica", "bold");
    doc.text(`Risk Level: ${tx.risk_level} Risk`, 20, 105);
    doc.text(`Risk Score: ${tx.risk_score}/100`, 20, 112);
    doc.text(`Fraud Detected: ${tx.risk_score > 50 ? 'Yes' : 'No'}`, 110, 105);
    doc.text(`Confidence Score: ${(Math.max(tx.risk_score, 100 - tx.risk_score) * 0.95).toFixed(1)}%`, 110, 112);
    doc.setTextColor(0);

    doc.setFont("helvetica", "bold");
    doc.text("Risk Factors & Flags:", 20, 128);
    doc.setFont("helvetica", "normal");
    let yPos = 135;
    if (tx.flags.length > 0) {
      tx.flags.forEach(flag => {
        doc.text(`• ${flag}`, 25, yPos);
        yPos += 7;
      });
    } else {
       doc.text("No significant risk factors flagged by rules engine.", 25, yPos);
       yPos += 7;
    }
    
    yPos += 5;
    doc.setFont("helvetica", "bold");
    doc.text("Recommendations:", 20, yPos);
    doc.setFont("helvetica", "normal");
    yPos += 7;
    if (tx.risk_score > 70) {
      doc.text("• Block the transaction immediately.", 25, yPos);
      doc.text("• Restrict user account and require 2FA identity validation.", 25, yPos + 7);
    } else if (tx.risk_score > 30) {
      doc.text("• Place transaction under manual review queue.", 25, yPos);
      doc.text("• Monitor user account for further anomalous activity.", 25, yPos + 7);
    } else {
      doc.text("• Proceed with authorization normally.", 25, yPos);
    }
    
    doc.setFontSize(9);
    doc.setTextColor(150);
    doc.text("Generated by FraudGuard Fraud Detection System", 105, 280, { align: 'center' });
    doc.text(`Report generated on: ${new Date().toLocaleString()}`, 105, 285, { align: 'center' });
    
    doc.save(`fraud-report-${tx.id}.pdf`);
  };

  const exportCSV = () => {
    const headers = ["ID", "Timestamp", "Amount", "Merchant", "Category", "IP", "Risk Score", "Risk Level", "Flags"];
    const rows = filtered.map(t => [
      t.id, 
      t.timestamp, 
      t.amount, 
      `"${t.merchant}"`, 
      t.category, 
      t.ip_address, 
      t.risk_score, 
      t.risk_level, 
      `"${t.flags.join(', ')}"`
    ]);
    
    const csvContent = "data:text/csv;charset=utf-8," + [headers.join(","), ...rows.map(e => e.join(","))].join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `transaction_history_${Date.now()}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  const filtered = history.filter(t => t.id.toLowerCase().includes(searchTerm.toLowerCase()) || t.merchant.toLowerCase().includes(searchTerm.toLowerCase()));

  return (
    <div className="p-4 md:p-8 space-y-6 max-w-7xl mx-auto">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-slate-200 dark:border-white/5 pb-4">
        <h1 className="text-2xl font-semibold tracking-tight">Transaction History</h1>
        
        <div className="flex items-center gap-2">
          <button onClick={exportCSV} className="flex items-center gap-2 px-3 py-2 bg-white dark:bg-black/20 border border-slate-200 dark:border-white/10 rounded-xl hover:bg-slate-50 dark:hover:bg-white/5 transition-colors text-sm font-medium">
            <FileSpreadsheet className="w-4 h-4 text-emerald-500" />
            <span className="hidden sm:inline">Export CSV</span>
          </button>
          <button onClick={() => window.print()} className="flex items-center gap-2 px-3 py-2 bg-white dark:bg-black/20 border border-slate-200 dark:border-white/10 rounded-xl hover:bg-slate-50 dark:hover:bg-white/5 transition-colors text-sm font-medium">
            <Printer className="w-4 h-4 text-blue-500" />
            <span className="hidden sm:inline">Print</span>
          </button>
        </div>
      </div>

      <div className="flex flex-col sm:flex-row justify-between gap-4">
        <div className="relative w-full sm:w-80">
          <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
          <input 
            type="text" 
            placeholder="Search ID or Merchant..." 
            value={searchTerm}
            onChange={(e) => setSearchTerm(e.target.value)}
            className="pl-9 pr-4 py-2 bg-white dark:bg-black/20 border border-slate-200 dark:border-white/10 rounded-xl text-sm focus:outline-none focus:ring-2 focus:ring-rose-500/50 w-full transition-all"
          />
        </div>
        <button className="p-2 bg-white dark:bg-black/20 border border-slate-200 dark:border-white/10 rounded-xl hover:bg-slate-50 dark:hover:bg-white/5 transition-colors">
          <Filter className="w-4 h-4 text-slate-500" />
        </button>
      </div>

      <div className="bg-white dark:bg-[#111623] border border-slate-200 dark:border-white/5 rounded-2xl overflow-hidden shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full text-sm text-left">
            <thead className="text-xs text-slate-500 dark:text-slate-400 uppercase bg-slate-50 dark:bg-black/20 border-b border-slate-200 dark:border-white/5">
              <tr>
                <th className="px-6 py-4 font-medium">Transaction ID</th>
                <th className="px-6 py-4 font-medium">Timestamp</th>
                <th className="px-6 py-4 font-medium">Amount</th>
                <th className="px-6 py-4 font-medium">Merchant</th>
                <th className="px-6 py-4 font-medium">Risk Status</th>
                <th className="px-6 py-4 font-medium text-right">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-white/5">
              {filtered.map((tx) => (
                <tr key={tx.id} className="hover:bg-slate-50 dark:hover:bg-white/5 transition-colors">
                  <td className="px-6 py-4 font-mono text-slate-700 dark:text-slate-300">
                    {tx.id}
                  </td>
                  <td className="px-6 py-4 text-slate-500">
                    {new Date(tx.timestamp).toLocaleString()}
                  </td>
                  <td className="px-6 py-4 font-medium text-slate-900 dark:text-white">
                    ${tx.amount.toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}
                  </td>
                  <td className="px-6 py-4 text-slate-700 dark:text-slate-300">
                    {tx.merchant}
                  </td>
                  <td className="px-6 py-4">
                    <span className={cn("px-2.5 py-1 text-xs rounded-md border font-medium shadow-sm inline-flex", getRiskColor(tx.risk_level))}>
                      {tx.risk_level}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-right">
                     <button
                       onClick={() => downloadReport(tx)}
                       className="p-1.5 text-slate-400 hover:text-rose-500 bg-slate-100 hover:bg-rose-50 dark:bg-white/5 dark:hover:bg-rose-500/10 rounded-md transition-colors inline-block"
                       title="Download PDF Report"
                     >
                        <FileText className="w-4 h-4" />
                     </button>
                  </td>
                </tr>
              ))}
              {filtered.length === 0 && (
                <tr>
                   <td colSpan={6} className="px-6 py-8 text-center text-slate-500">
                     No transactions found matching '{searchTerm}'.
                   </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
